networks:
  aqua-sharp:
    external: true

services:
  aqua-sharp-frontend:
    container_name: aqua-sharp-frontend
    image: gromat/aqua-sharp-frontend:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - aqua-sharp
    depends_on:
      - eclipse-mosquitto
      - aqua-sharp-backend

  aqua-sharp-backend:
    container_name: aqua-sharp-backend
    image: gromat/aqua-sharp-backend:latest
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - aqua-sharp
    depends_on:
      - eclipse-mosquitto

  eclipse-mosquitto:
    container_name: mosquitto
    image: docker.io/eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /mosquitto/data
      - /mosquitto/log
      - ./conf:/mosquitto/config
    networks:
      - aqua-sharp