version: "3"
services:
  eclipse-mosquitto:
    image: docker.io/eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /mosquitto/data
      - /mosquitto/log
      - ./conf:/mosquitto/config

  database:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=FkbpXP55&Tm2gh5b
    volumes:
      - ./data:/var/opt/mssql/data