networks:
  aqua-sharp:
    external: true

services:
  aqua-sharp:
    container_name: aqua-sharp
    image: aqua-sharp-backend:latest
    restart: unless-stopped
    ports:
      - 80:80
    networks:
      - aqua-sharp
    depends_on:
      - eclipse-mosquitto
      - database

  eclipse-mosquitto:
    container_name: mosquitto
    image: docker.io/eclipse-mosquitto
    restart: unless-stopped
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - /mosquitto/data
      - /mosquitto/log
      - ./conf:/mosquitto/config
    networks:
      - aqua-sharp

  database:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=FkbpXP55&Tm2gh5b
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
      - aqua-sharp
